version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1
  eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - node/install:
          node-version: '14.17'
      - run: node --version
      - checkout
      - aws-cli/setup
      - eb/setup
      - run:
          name: Install Frontend Packages
          command: |
            npm run frontend:install
      - run:
        name: Install Backend Packages
        command: |
          npm run backend:install
      - run:
          name: Build Frontend
          command: |
            npm run frontend:build
      - run:
          name: Build Backend
          command: |
            npm run backend:build
      - run:
          name: Deploy Frontend
          command: |
            npm run frontend:deploy
      - run:
          name: Deploy Backend
          command: |
            npm run backend:deploy
