version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1
  browser-tools: circleci/browser-tools@1.2.3
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install:
          node-version: '14.17'
      - run: node --version
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - checkout
      - aws-cli/setup
      - run:
          name: Install Packages
          command: |
            npm install
      - run:
          name: Lint
          command: |
            npm run lint
      - run:
          name: Tests
          command: |
            npm run test:ci
      - run:
          name: Build App
          command: |
            npm run build
      - run:
          name: Deploy App
          command: |
            npm run deploy

